server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /app

logging:
  level:
    org.springframework.boot: INFO
    ua.ellka: DEBUG

management:
  endpoint:
    beans:
      access: read_only
    metrics:
      access: unrestricted

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://${JDBC_DB_HOST}/${JDBC_DB_NAME}
    password: ${JDBC_DB_PASSWORD}
    username: ${JDBC_DB_USER}
    driver-class-name: com.mysql.cj.jdbc.Driver